import 'package:flutter/material.dart';

const Color firstBorderColor = Color(0xFF026BCE);
const Color firstToggleColor = Color(0xFFE1E1E1);
const Color firstActiveColor = Color(0xFF33E2FF);
const Color firstInactiveColor = Colors.black38;
const Color secondActiveColor = Color(0xFF271052);
const Color secondInactiveColor = Colors.white;
const Color thirdActiveColor = Color(0xFF55DDCA);
const Color thirdInactiveColor = Color(0xFF54C5F8);
const Color firstActiveTextColor = Colors.black;
final Color firstInactiveTextColor = Colors.blue[50]!;
const Color firstActiveToggleColor = Color(0xFF6E40C9);
const Color firstInactiveToggleColor = Color(0xFF2F363D);
const Color secondActiveToggleColor = Color(0xFF0082C8);
const Color secondInactiveToggleColor = Color(0xFF01579B);
const Color firstActiveBorderColor = Color(0xFF3C1E70);
const Color firstInactiveBorderColor = Color(0xFFD1D5DA);
const Color secondActiveBorderColor = Color(0xFF00D2B8);
const Color secondInactiveBorderColor = Color(0xFF29B6F6);
const Color moonIconColor = Color(0xFFF8E3A1);
const Color sunIconColor = Color(0xFFFFDF5D);
