// Mocks generated by Mockito 5.4.6 from annotations
// in mobile1_flutter_coding_test/test/features/chat/data/repositories/chat_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile1_flutter_coding_test/features/chat/data/models/chat_room_list_response.dart'
    as _i2;
import 'package:mobile1_flutter_coding_test/features/chat/data/sources/chat_api_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatRoomListResponse_0 extends _i1.SmartFake
    implements _i2.ChatRoomListResponse {
  _FakeChatRoomListResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatApiService extends _i1.Mock implements _i3.ChatApiService {
  MockChatApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ChatRoomListResponse> getChatRooms() =>
      (super.noSuchMethod(
            Invocation.method(#getChatRooms, []),
            returnValue: _i4.Future<_i2.ChatRoomListResponse>.value(
              _FakeChatRoomListResponse_0(
                this,
                Invocation.method(#getChatRooms, []),
              ),
            ),
          )
          as _i4.Future<_i2.ChatRoomListResponse>);
}
