// Mocks generated by Mockito 5.4.6 from annotations
// in mobile1_flutter_coding_test/test/data/datasource/chat_room_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile1_flutter_coding_test/core/network/request_api.dart'
    as _i2;
import 'package:mobile1_flutter_coding_test/data/datasource/chat_room_datasource.dart'
    as _i3;
import 'package:mobile1_flutter_coding_test/data/model/chat_room_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseResult_0<T> extends _i1.SmartFake
    implements _i2.ResponseResult<T> {
  _FakeResponseResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatRoomDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRoomDatasource extends _i1.Mock
    implements _i3.ChatRoomDatasource {
  MockChatRoomDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResponseResult<_i5.ChatRoomListModel>> getChatRooms() =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatRooms,
          [],
        ),
        returnValue:
            _i4.Future<_i2.ResponseResult<_i5.ChatRoomListModel>>.value(
                _FakeResponseResult_0<_i5.ChatRoomListModel>(
          this,
          Invocation.method(
            #getChatRooms,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ResponseResult<_i5.ChatRoomListModel>>);
}
