// Mocks generated by Mockito 5.4.6 from annotations
// in mobile1_flutter_coding_test/test/data/datasource/room_message_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile1_flutter_coding_test/core/network/request_api.dart'
    as _i2;
import 'package:mobile1_flutter_coding_test/data/datasource/room_message_datasource.dart'
    as _i3;
import 'package:mobile1_flutter_coding_test/data/model/message_model.dart'
    as _i5;
import 'package:mobile1_flutter_coding_test/domain/entity/message.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseResult_0<T> extends _i1.SmartFake
    implements _i2.ResponseResult<T> {
  _FakeResponseResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RoomMessageDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoomMessageDatasource extends _i1.Mock
    implements _i3.RoomMessageDatasource {
  MockRoomMessageDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> hasMessages() => (super.noSuchMethod(
        Invocation.method(
          #hasMessages,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.ResponseResult<_i5.MessageListModel>> getRoomMessages() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoomMessages,
          [],
        ),
        returnValue: _i4.Future<_i2.ResponseResult<_i5.MessageListModel>>.value(
            _FakeResponseResult_0<_i5.MessageListModel>(
          this,
          Invocation.method(
            #getRoomMessages,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ResponseResult<_i5.MessageListModel>>);

  @override
  _i4.Future<Map<String, List<Map<String, dynamic>>>>
      getRoomMeesagesByStorage() => (super.noSuchMethod(
            Invocation.method(
              #getRoomMeesagesByStorage,
              [],
            ),
            returnValue:
                _i4.Future<Map<String, List<Map<String, dynamic>>>>.value(
                    <String, List<Map<String, dynamic>>>{}),
          ) as _i4.Future<Map<String, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<void> saveRoomMeesagesToStorage(
          Map<String, List<Map<String, dynamic>>>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRoomMeesagesToStorage,
          [messages],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addMessageToStorage(
    String? roomId,
    _i6.Message? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMessageToStorage,
          [
            roomId,
            message,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setHasMessages(bool? hasMessages) => (super.noSuchMethod(
        Invocation.method(
          #setHasMessages,
          [hasMessages],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
