// Mocks generated by Mockito 5.4.4 from annotations
// in mobile1_flutter_coding_test/test/layers/data/source/repository/meeting_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile1_flutter_coding_test/layers/data/entity/meeting_room_dto.dart'
    as _i5;
import 'package:mobile1_flutter_coding_test/layers/data/entity/user_dto.dart'
    as _i4;
import 'package:mobile1_flutter_coding_test/layers/data/source/remote/remote_data_sources.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RemoteDataSources].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSources extends _i1.Mock implements _i2.RemoteDataSources {
  MockRemoteDataSources() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.UserDTO>> fetchUsers() => (super.noSuchMethod(
        Invocation.method(
          #fetchUsers,
          [],
        ),
        returnValue: _i3.Future<List<_i4.UserDTO>>.value(<_i4.UserDTO>[]),
      ) as _i3.Future<List<_i4.UserDTO>>);

  @override
  _i3.Future<List<_i5.MeetingRoomDTO>> fetchMeetingRoom() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMeetingRoom,
          [],
        ),
        returnValue:
            _i3.Future<List<_i5.MeetingRoomDTO>>.value(<_i5.MeetingRoomDTO>[]),
      ) as _i3.Future<List<_i5.MeetingRoomDTO>>);
}
