name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
  release:
    types: [published]

### pr과 release 구분
#  기본 pr시는 빌드만
jobs:
  quality:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Build Android APK
        run: flutter build apk --debug

      - name: Build iOS app
        run: flutter build ios  --simulator

  # 릴리즈 시에는 apk업로드
  release:
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up tooling
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests again
        run: flutter test --no-pub

      # Android
      - name: Clean build artifacts
        if: matrix.os == 'ubuntu-latest'
        run: flutter clean

      - name: Build Android APK
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      # iOS
      - name: Build iOS
        if: matrix.os == 'macos-latest'
        env:
          FLUTTER_XCODE_CODE_SIGN_STYLE: Manual
        run: |
          flutter clean
          flutter build ios --simulator


      # Android APK만 업로드
      - name: Upload Android APK
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: build/app/outputs/**/*.apk

      - name: Upload APK to Release
        if: github.event_name == 'release' && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk

#워크플로 동시 실행 방지                                     #
concurrency:
  group: flutter-ci-${{ github.ref }}
  cancel-in-progress: true