name: github_actions
on:
  push:
    branches:
      - codingtest
  pull_request:
jobs:
  build:
    name: running tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      #https://github.com/subosito/flutter-action
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: Import Flutter Package
        run: |
          flutter pub get
      - name: Test Flutter
        run: |
          flutter test