name: 릴리즈

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: 릴리즈 생성
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4
      
    - name: 릴리즈 생성
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  build-android:
    name: Android 릴리즈 빌드
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4
      
    - name: Flutter SDK 설정
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        
    - name: 의존성 설치
      run: flutter pub get
      
    - name: 코드 생성 (build_runner)
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Java 설정
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Android APK 빌드
      run: flutter build apk --release --android-skip-build-dependency-validation
      
    - name: Android Bundle 빌드
      run: flutter build appbundle --release --android-skip-build-dependency-validation
      
    - name: APK 업로드
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: rsupport-${{ github.ref_name }}.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Bundle 업로드
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: build/app/outputs/bundle/release/app-release.aab
        asset_name: rsupport-${{ github.ref_name }}.aab
        asset_content_type: application/octet-stream

  build-ios:
    name: iOS 릴리즈 빌드
    runs-on: macos-latest
    needs: create-release
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4
      
    - name: Flutter SDK 설정
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        
    - name: 의존성 설치
      run: flutter pub get
      
    - name: 코드 생성 (build_runner)
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: iOS 빌드
      run: flutter build ios --release --no-codesign
      
    - name: iOS 아카이브 생성
      run: |
        cd build/ios/iphoneos
        tar -czf ../../../rsupport-ios-${{ github.ref_name }}.tar.gz Runner.app
        
    - name: iOS 아카이브 업로드
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: rsupport-ios-${{ github.ref_name }}.tar.gz
        asset_name: rsupport-ios-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip

  build-web:
    name: Web 릴리즈 빌드
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4
      
    - name: Flutter SDK 설정
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        
    - name: 의존성 설치
      run: flutter pub get
      
    - name: 코드 생성 (build_runner)
      run: flutter packages pub run build_runner build --delete-conflicting-outputs
      
    - name: Web 빌드
      run: flutter build web --release
      
    - name: Web 아카이브 생성
      run: |
        cd build
        tar -czf ../rsupport-web-${{ github.ref_name }}.tar.gz web/
        
    - name: Web 아카이브 업로드
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: rsupport-web-${{ github.ref_name }}.tar.gz
        asset_name: rsupport-web-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip 